<div id="oneArticle"> 

        <article> 
            <h1><?= $article['titre'] ?></h1> 
            <img src="../img/<?= $article['img'] ?> " alt="" style="max-width: 100%;">
            <h4>Sujet : <?= $article['sujet'] ?></h4> 
            <p><em>Date de creation : <?= $article['dateCreation'] ?></em></p> 
            <p><?= $article['description'] ?></p>
            <p><em>Rédigé par : <?= $article['auteur'] ?></em></p> 

        </article> 
</div>
