<div class="articleHead">
    <h1>MODIFIER LE PROFIL</h1>
</div>


<div id="editUser"> 

    <form class="form-group row" action="/php/updateProfil.php" method="post">
        <label for="pseudo" class="col-sm-2 form-control-label">Pseudonyme :</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="pseudo" name="pseudo" value="<?= $user['pseudo'] ?>">
        </div>

        <label for="nom" class="col-sm-2 form-control-label">Nom : </label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="nom"  name="nom" value="<?= $user['nom'] ?>">
        </div>

        <label for="prenom" class="col-sm-2 form-control-label">Prénom</label>
        <div class="col-sm-10">
            <input rows="30" type="text" class="form-control" id="prenom"  name="prenom" value="<?= $user['prenom'] ?>">
        </div>

        <label for="mail" class="col-sm-2 form-control-label">Mail</label>
        <div class="col-sm-10">
            <input rows="30" type="text" class="form-control" id="mail"  name="mail" value="<?= $user['mail'] ?>">
        </div>

        <input type="hidden" name="id" value="<?= $user['id'] ?>">

        <button type="submit" class="btn btn-warning ">Valider</button>

    </form>



</div>
