<div class="articleHead">
    <h1>ACCUEIL</h1>
</div>
                <p>
                    Dragon Ball Z, LE manga ultime. Suite de Dragon Ball qui met en avant les aventures de Sangoku, "DBZ" fait passer ce manga de petit dessin animé marrant à un niveau supérieur.
                    Une intensité rare, un humour à toutes épreuves, des méchants charismatiques et une histoire touchante.
                </p>
                <p>
                    Dans ce dernier, le héros principal n'est plus Sangoku mais son fils Sangohan, timide, il réserve d'énorme surprise (aussi bien bonne que mauvaise) tout au long des 291 épisodes.
                    Il s'agit pour moi du meilleur manga de l'histoire des manga, sans aucune hésitation.
                </p>

                <p>
                    Bon venons en au fait, sur ce site vous trouverez des infos, des photos et l’histoire de Dragon-Ball Z, n’hésitez pas à me faire part de vos remarques et vos conseils.
                    <a href="php/article.php?ref=1">Mon premier article</a>
                    <a href="php/article.php?ref=2">Mon deuxieme article</a>
                </p>




    