<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap -->
    <link type="text/css" href="/RECUP/css/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap social -->
    <link type="text/css" rel="stylesheet" href="/RECUP/css/bootstrap-social-gh-pages/bootstrap-social.css">
   
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">
    <script
        src="https://code.jquery.com/jquery-1.12.4.min.js"
        integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
        crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/d78a38dbf9.js"></script>
    <!-- Latest compiled and minified CSS -->
   <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">-->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="/RECUP/css/Rpg-Awesome-master/css/rpg-awesome.min.css">
    <link type="text/css" rel="stylesheet" href="/RECUP/css/layout.css">
    <link type="text/css" rel="stylesheet" href="/RECUP/css/style.css">

    <script src="/RECUP/js/effects.js"></script>

    <title>DBZ-LIFE</title>

</head>
<body>
<header>




    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">DBZ LIFE</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="/RECUP/index.php">ACCUEIL</a></li>
                <li><a href="#">MONDE</a></li>
                <li><a href="/RECUP/php/blog.php">BLOG</a></li>
                <li><a href="#">CONTACT</a></li>
                <?php if (isset($_SESSION['connected']) AND $_SESSION['role'] == 'admin') : ?>
                <li><a href="php/admin.php">ADMIN</a></li>
                <?php endif; ?>
            </ul>
        </div>
    </div>


    <h1 class="title">DBZ-LIFE</h1>




</header>




<!--------- DEBUT DU CONTAINER ------------>

<div class="container">
    <div id="row" class="row" style="display: none">


        <div class="col-md-8 col-md-offset-0 col-sm-6 col-sm-offset-1 col-xs-10 col-xs-offset-1" id="centre">


                <?php include $template.'.phtml' ?>





        </div>

        <div class="asides col-md-3 col-md-offset-1 col-sm-4 col-sm-offset-1 col-xs-10 col-xs-offset-1">
            <aside><!--- MON COMPTE --->
                <div class="asideHead">
                    <h2>Mon compte</h2>
                </div>



                <?php if (isset($_SESSION['connected'])){ ?>
                <ul>
                    <li><a href="/php/logout.php"><button type="button" class="btn btn-warning ">Déconnexion</button></a></li>
                    <hr>
                    <li><a href="/php/myaccount.php"><button type="button" class="btn btn-warning ">Mon compte</button></a></li>
                </ul>
                <?php } else { ?>
                <ul>
                    <li><a href="/php/login.php"><button type="button" class="btn btn-warning ">Connexion</button></a></li>
                    <hr>
                    <li><a href="#"><button type="button" class="btn btn-warning ">Inscription</button></a></li>
                </ul>
                <?php } ?>

            </aside>


            <aside><!--- SOCIAL --->

                <div class="asideHead">
                    <h2>Suivez-nous : </h2>
                </div>

                <a href="https://twitter.com/Fareswilliams" class="btn btn-social-icon btn-twitter">
                    <span class="fa fa-twitter"></span>
                </a>
                <a class="btn btn-social-icon btn-facebook">
                    <span class="fa fa-facebook"></span>
                </a>
                <a class="btn btn-social-icon btn-instagram">
                    <span class="fa fa-instagram"></span>
                </a>
                <a class="btn btn-social-icon btn-google">
                    <span class="fa fa-google"></span>
                </a>

            </aside>


        </div><!---- FIN DE DIV ASIDES --->
    </div><!---- fin div row --->

</div>
<!--------------- FIN DU CONTAINER ---------------->



<footer>
    <p>© 2017	| Fièrement propulsé par	Fares Junior | Theme: DBZ-LIFE</p>
</footer>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/RECUP/css/bootstrap/js/bootstrap.min.js"></script>





</body>
</html>

