<div class="articleHead">
    <h1>CONNEXION</h1>
</div>



<form method="post" action="/php/login.php">

<?php if (isset($errorMessage)) { ?>
<div class="errorMessage"><?= $errorMessage ?></div>
<?php } ?>

    <div class="form-group row">
        <label for="inputEmail3" class="col-sm-2 form-control-label">Pseudo</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="inputEmail3" placeholder="Pseudo" name="pseudo">
        </div>
    </div>


    <div class="form-group row">
        <label for="inputPassword3" class="col-sm-2 form-control-label">Mot de passe</label>
        <div class="col-sm-10">
            <input type="password" class="form-control" id="inputPassword3" placeholder="Mot de passe" name="password">
        </div>
    </div>

    <button type="submit" class="btn btn-warning ">Valider</button>
</form>